services:
  app_mym_dental:
    build: MyMDentistComerce
    ports:
      - "8080:8080"
    environment:
      AWS_BUCKET_NAME: name
      PUBLIC_KEY: a
      SECRET_KEY: b
      TOKEN_KEY: c
      DB_PATH: d
      DB_USER: e
      DB_PASS: f
      LOCAL_PATH: g
      CLOUDFRONT_PATH: h
      S3_BUCKET_PAGE: i
    restart: always