spring.application.name=mym_dentist_commerce
server.port = 8080

#Conection database

# Database connection settings
spring.datasource.url=${DB_PATH:jdbc:mysql://MyMDentistComerce_db:3306/mymdentistcomerce?createDatabaseIfNotExist=true&serverTimezone=UTC}
#spring.datasource.url=jdbc:mysql://localhost:3306/mymdentistcomerce
spring.datasource.username=${DB_USER:root}
#spring.datasource.username=root
spring.datasource.password=${DB_PASS: }
#spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Spring security

aws.s3.bucket.name=${AWS_BUCKET_NAME:s3-bucket-test-spring}

aws.accessKeyId=${PUBLIC_KEY:ASIAXEV7N7NMTRBE7OLO}
aws.secretKey=${SECRET_KEY:oll0vF8DrnvZB/5ESYzTGFuePhsXL2gHBkQByM5W}
aws.sessionToken=${TOKEN_KEY:IQoJb3JpZ2luX2VjEP3//////////wEaCXVzLXdlc3QtMiJHMEUCIQCouIMRb1tkeW1KTqg3SejQTePi2jCt6vY0omMzirverwIgdFTdb/QhbryjsGg3B7/LpFO8ZAZwLE2dRzsuMTWcL8UqrwIIxv//////////ARABGgw0OTExMDE0ODU5MTMiDCdIZOKjfBCmEnrwaiqDAo9Ig/pH1hHsbcPxtq9sxkLhuXY2L5WmVBQYZDnjMLs6zf/VbD44+N+so1ClbWQs6J52GBRZ8vS9sAmoyDAKJBwnc1G8XglDQ+W/THNOk4x3kEWvrbtaSSoYBUhPOOGXB2RYfuKL5SrpQoLHci1YkJmlxUInFgVeO01P3u/SpUQjPmAdxx4kM2ctnQsonETg6GSCDtIpLPMztoWsRSE7kEcUgr2ry6bfFl6/jaZFbhh6OS/K28EOLv23wQ7jSkmErULXu1HCQIJQsTAGSdOmHyu5dLr6J3kCxt2pP76QaqaCu+DBLmye3u0CfgMxp8SMJL1QQBIXwIs805odTiIHbmv1JLMw9+qt0AY6nQF7FPOMXGRHPDoOOfpUoFHfxidpACeFb/nxjykwJqItRljLWvwTA4L4n5KNA00+LrGOilg7zfXn0VysF86MuP0inytvGb8RqFQ2ZtcgcfLb8isUjvIicmIAMj+dz0WBCK7LAz14bdKKJaIAFJpfGcpaAO7jN5nOMNpRQNu43zwdIR9HHgJq09cMbQYx3t06gl5PS7f7iyBIVIgl0D+X}

# CORS Config
spring.cors.origins.test=${LOCAL_PATH}
spring.cors.origins.cloudfront=${CLOUDFRONT_PATH}
spring.cors.origins.s3Bucket=${S3_BUCKET_PAGE}

