spring.application.name=mym_dentist_commerce
server.port = 8080

#Conection database

# Database connection settings
spring.datasource.url=${DB_PATH:jdbc:mysql://MyMDentistComerce_db:3306/mymdentistcomerce?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=
#spring.datasource.username=root
spring.datasource.password=
#spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Spring security

aws.s3.bucket.name=





# CORS Config
spring.cors.origins.test=
spring.cors.origins.cloudfront=
spring.cors.origins.s3Bucket=

